package enums;

public enum ObjectTypes {
	OBJECT_TYPE_UNKOWN,
	OBJECT_TYPE_PLAYER,
	OBJECT_TYPE_GRUNT,
	OBJECT_TYPE_MAN,
	OBJECT_TYPE_WOMAN ,
	OBJECT_TYPE_MIKEY,
	OBJECT_TYPE_HULK,
	OBJECT_TYPE_SPHERIODS,
	OBJECT_TYPE_ENFORCERS,
	OBJECT_TYPE_FAMILY_DEATH,
	OBJECT_TYPE_OBSTACLE,
	OBJECT_TYPE_PLAYER_MISSLE;
}
